# SPDX-FileCopyrightText: 2025 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: CC0-1.0

repos:
# keep-sorted start
- repo: https://github.com/fsfe/reuse-tool
  rev: v5.0.2
  hooks:
  - id: reuse
- repo: https://github.com/google/keep-sorted
  rev: v0.6.0
  hooks:
  - id: keep-sorted
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
# keep-sorted end
